### ISSUE TITLE
thanks bro, only 1 question, :)

### ISSUE THREAD

**Issue by bettonna** [MrAndrewBlood/Captcha-Solver#1]
thank you for your effort bro , only I want to ask that, if possible Can you add this solver to chrome store please , like extension?? we can use in chrome like that, thanks again , have a good day

**Comment by MrAndrewBlood** [comment]
Sry I have tested it with Type/Javascript but no more chance, because with Javascript (Extension and script programming language) I have bypassed the close shadow root and it click the button but I cannot bypass the click looking...
So on it comes everytime "Error" 

Yet I maked the search and click function with python.

Greeds Andrewblood
